### ISSUE TITLE
Windows instructions?

### ISSUE THREAD

**Issue by strunker** [NVISO-BE/IOXY#3]
Hello, 

I am not all that familiar with Go but I followed the instructions there was an additional compiler I had to install to get Go to properly build it. Anyway, ioxy.exe was built and when I run it with the gui switch. I see the below, but no actual UI ever opens up? Any suggestions? Thanks much.

![image](https://user-images.githubusercontent.com/6154660/118500626-f34bb580-b6f5-11eb-8928-bac45cc9ffa1.png)

**Comment by windBlaze** [comment]
Hi there! IOXY has a web-based GUI, which means that you have to access it using your browser :) Once you launch it with the "ioxy gui" command (like in your screenshot), just open your browser of choice and navigate to http://localhost:1111 ! If that fails, please let me know and I'll investigate further.

**Comment by strunker** [comment]
> Hi there! IOXY has a web-based GUI, which means that you have to access it using your browser :) Once you launch it with the "ioxy gui" command (like in your screenshot), just open your browser of choice and navigate to http://localhost:1111 ! If that fails, please let me know and I'll investigate further.

Thanks much for this. I was able to get it going :) the below is all really necessary in order to get it up and running and capturing. From there you just go to loopback in the browser and the port and you are fine. I didnt connect the dots the interface was web based I should have put that together seeing 0.0.0.0 in the console output. Thank you. 

ioxy mqtt broker mitm-opt gui

**Comment by windBlaze** [comment]
Glad you got it working :) Don't hesitate to let us know if you run into any other issues / bugs !
