### ISSUE TITLE
MQTTS without Client Authentication

### ISSUE THREAD

**Issue by byte-arts** [NVISO-BE/IOXY#5]
Hello,

first thank you for your great work!

I wanted to know if it is possible to use mqtts without client authentication. I wasn't able to configure IOXY this way...

Am i missing something or is this feature not available?

Best Regards,
byte-arts

**Comment by hutchYy** [comment]
Hi @byte-arts!

The features is indeed not yet implemented :)
The feature has been added to our roadmap!

Thanks for your feedback!

Best regards,
hutchYy
