### ISSUE TITLE
error on go build .

### ISSUE THREAD

**Issue by manikandanbaskarans** [NVISO-BE/IOXY#6]
while running go build . throws the following error in windows
"cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%"

Thankyou

**Comment by hutchYy** [comment]
Hey!

You might be missing the gcc compiler.
On Windows install http://tdm-gcc.tdragon.net/download
Once installed, try again and it should work!

Have a nice day!
hutchYy
