### ISSUE TITLE
Error to go build . 

### ISSUE THREAD

**Issue by k4n4n** [NVISO-BE/IOXY#7]
Hi!

I have this error when installing IOXY in my machine

![IOXYError](https://user-images.githubusercontent.com/43685859/140950487-7eed541d-67e4-481f-877f-c99a1de3c8ee.png)

I don't seem to have read permissions on some additional repositories

could you help me with this,

thanks

regards,

**Comment by windBlaze** [comment]
Hi! Thank you for the report, it seems that this dependency was removed from github :/ We are working on providing an alternative !

**Comment by windBlaze** [comment]
Fixed in https://github.com/NVISOsecurity/IOXY/commit/8be710cf7b03bc8709de0ed916dae02637a3c02f :) The build should now work normally again!
